spring:
  profiles: oauth2
  
oauth2:
  jwt:
    clientId: oath2Client
    client-secret: secret
    signing-key: 123
    scope: read,write
    authorities: ROLE_CLIENT,ROLE_TRUSTED_CLIENT,ROLE_USER,ROLE_ADMIN
    authorizedGrantTypes: password,authorization_code,refresh_token
    accessTokenValidititySeconds: 43200 #12 hours
    refreshTokenValiditySeconds: 2592000 #30 days
    
    